export interface ClinicalHistory {
  folderId: string
  patientId: string
  numeroHc: string
  convenio: string
  fecha: string
  nombresApellidos: string
  nroIdentificacion: string
  fechaNacimiento: string
  edad: string
  genero: string
  estadoCivil: string
  escolaridad: string
  profesionOcupacion: string
  telefono: string
  domicilio: string
  canton: string
  provincia: string
  pais: string
  direccion: string
  nacionalidad: string
  motivoConsulta: string
  cardiovasculares: string
  metabolicos: string
  renales: string
  digestivos: string
  quirurgicos: string
  alergicos: string
  transfusiones: string
  medicamentos: string
  alcohol: string
  drogas: string
  tabaquismo: string
  otrosHabitos: string
  madre: string
  hijos: string
  padre: string
  hermanos: string
  menarquia: string
  cicloMenstrual: string
  partos: string
  sexarquia: string
  fum: string
  gestaciones: string
  abortos: string
  anticonceptivos: string
  cesareas: string
  enfermedadActual: string
  presionArterial: string
  pesoKg: string
  imc: string
  frecuenciaCardiaca: string
  talla: string
  frecuenciaRespiratoria: string
  temperatura: string
  sat: string
  updatedAt: string
}

export type ClinicalHistoryInput = Omit<ClinicalHistory, 'updatedAt'>
